version: '3'
services:
  backend:
    restart: always
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
  frontend:
    restart: always
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true